# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: gregory.mooney@quantstack.net
author_name: Greg Mooney
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: jupyterlab_arpresent
mimetype: ''
mimetype_name: ''
project_short_description: Video presentation over WebRTC with AR capabilities.
python_name: jupyterlab_arpresent
repository: https://github.com/gjmooney/jupyterlab-arpresent
test: true
viewer_name: ''

